AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Pipeline for continuous delivery of Save2Memrise app which consists of EC2
  service and S3 bucket. 
Parameters:
  ProjectNameTag:
    Type: String
    Default: save2memrise
  GitHubOwner:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  TestMemrisePassword:
    Type: String
    NoEcho: true
  BlueProdChromeExtBucketName: 
    Type: String
    Description: S3 Bucket Name of the Chrome extension
  GreenProdChromeExtBucketName: 
    Type: String
    Description: S3 Bucket Name of the Chrome extension
  BlueProdChromeExtCloudfrontDistribution: 
    Type: String
    Description: CloudFront distribution ID of the Chrome extension
  GreenProdChromeExtCloudfrontDistribution: 
    Type: String
    Description: CloudFront distribution ID of the Chrome extension
  EcsClusterName:
    Type: String
  BlueProdPublicApiEcsService:
    Type: String
  GreenProdPublicApiEcsService:
    Type: String
Resources:
  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties: 
      Tags:
        - 
          Key: ProjectName
          Value: !Ref ProjectNameTag
  PipelineWebhook2:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      Filters:
        - 
          JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      Name: S2MPipelineWebhook2
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true
  TestPublicApiProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-TestPublicApi'
      Description: >- 
        Run tests for Public Api service
      Artifacts:
        Type: CODEPIPELINE
      #TODO Rid of hardcoded IDs
      ServiceRole: 'arn:aws:iam::321373361512:role/Save2MemriseCodeBuildProjectServiceRole'
      EncryptionKey: 'arn:aws:kms:eu-central-1:321373361512:alias/aws/s3'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: '321373361512.dkr.ecr.eu-central-1.amazonaws.com/save2memrise/build:0.1.0'
        PrivilegedMode: true
        ImagePullCredentialsType: SERVICE_ROLE
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: eu-central-1
          - Name: AWS_ACCOUNT_ID
            Value: 321373361512
          - Name: ENVIRONMENT
            Value: prod
          - Name: SAVE2MEMRISE_Memrise__Password
            Value: !Ref TestMemrisePassword
      Source:
        Type: CODEPIPELINE
        BuildSpec: test-public-api-buildspec.yml
      TimeoutInMinutes: 10
      Tags:
        - 
          Key: ProjectName
          Value: !Ref ProjectNameTag
  BuildPublicApiImageProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-BuildPublicApiImage'
      Description: >- 
        Build and push the docker image for Public Api service
      Artifacts:
        Type: CODEPIPELINE
      #TODO Rid of hardcoded IDs
      ServiceRole: 'arn:aws:iam::321373361512:role/Save2MemriseCodeBuildProjectServiceRole'
      EncryptionKey: 'arn:aws:kms:eu-central-1:321373361512:alias/aws/s3'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: '321373361512.dkr.ecr.eu-central-1.amazonaws.com/save2memrise/build:0.1.0'
        PrivilegedMode: true
        ImagePullCredentialsType: SERVICE_ROLE
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: eu-central-1
          - Name: AWS_ACCOUNT_ID
            Value: 321373361512
          - Name: IMAGE_REPO_NAME
            Value: save2memrise/public-api
          - Name: ENVIRONMENT
            Value: prod
      Source:
        Type: CODEPIPELINE
        BuildSpec: build-public-api-image-buildspec.yml
      TimeoutInMinutes: 10
      Tags:
        - 
          Key: ProjectName
          Value: !Ref ProjectNameTag
  BlueProdDeployChromeExtProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-BuildChromeExt-BlueProd'
      Description: Deploy Chrome Extension
      Artifacts:
        Type: CODEPIPELINE
      #TODO Rid of hardcoded IDs
      ServiceRole: 'arn:aws:iam::321373361512:role/Save2MemriseCodeBuildProjectServiceRole'
      EncryptionKey: 'arn:aws:kms:eu-central-1:321373361512:alias/aws/s3'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: '321373361512.dkr.ecr.eu-central-1.amazonaws.com/save2memrise/build:0.1.0'
        PrivilegedMode: true
        ImagePullCredentialsType: SERVICE_ROLE
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: eu-central-1
          - Name: AWS_ACCOUNT_ID
            Value: 321373361512
          - Name: CDN_DISTRIBUTION_ID
            Value: !Ref BlueProdChromeExtCloudfrontDistribution
          - Name: S3_BUCKET_NAME
            Value: !Ref BlueProdChromeExtBucketName
          - Name: ENVIRONMENT
            Value: prod-blue
      Source:
        Type: CODEPIPELINE
        BuildSpec: chrome-ext-buildspec.yml
      TimeoutInMinutes: 10
      Tags:
        - 
          Key: ProjectName
          Value: !Ref ProjectNameTag
  GreenProdDeployChromeExtProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-BuildChromeExt-GreenProd'
      Description: Deploy Chrome Extension
      Artifacts:
        Type: CODEPIPELINE
      #TODO Rid of hardcoded IDs
      ServiceRole: 'arn:aws:iam::321373361512:role/Save2MemriseCodeBuildProjectServiceRole'
      EncryptionKey: 'arn:aws:kms:eu-central-1:321373361512:alias/aws/s3'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: '321373361512.dkr.ecr.eu-central-1.amazonaws.com/save2memrise/build:0.1.0'
        PrivilegedMode: true
        ImagePullCredentialsType: SERVICE_ROLE
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: eu-central-1
          - Name: AWS_ACCOUNT_ID
            Value: 321373361512
          - Name: CDN_DISTRIBUTION_ID
            Value: !Ref GreenProdChromeExtCloudfrontDistribution
          - Name: S3_BUCKET_NAME
            Value: !Ref GreenProdChromeExtBucketName
          - Name: ENVIRONMENT
            Value: prod-green
      Source:
        Type: CODEPIPELINE
        BuildSpec: chrome-ext-buildspec.yml
      TimeoutInMinutes: 10
      Tags:
        - 
          Key: ProjectName
          Value: !Ref ProjectNameTag
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: 'arn:aws:iam::321373361512:role/AWS-CodePipeline-Service'
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - Name: SourceOutput
              Configuration: 
                Owner: !Ref GitHubOwner
                Repo: save2memrise
                Branch: master
                OAuthToken: !Ref GitHubOAuthToken
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: TestPublicApi
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref TestPublicApiProject
              RunOrder: 1
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              Configuration:
                CustomData: 'Approve image building'
              RunOrder: 2
            - Name: BuildPublicApiImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildPublicApiOutput
              Configuration:
                ProjectName: !Ref BuildPublicApiImageProject
              RunOrder: 3
        - Name: DeployToBlueProd
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              Configuration:
                CustomData: 'Approve deployment'
              RunOrder: 1
            - Name: DeployPublicApi
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: ECS
              InputArtifacts:
                - Name: BuildPublicApiOutput
              OutputArtifacts: []
              Configuration:
                ClusterName: !Ref EcsClusterName
                ServiceName: !Ref BlueProdPublicApiEcsService
                FileName: imagedefinitions.json
              RunOrder: 2
            - Name: DeployChromeExt
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts: []
              Configuration:
                ProjectName: !Ref BlueProdDeployChromeExtProject
              RunOrder: 3
        - Name: DeployToGreenProd
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              Configuration:
                CustomData: 'Approve deployment'
              RunOrder: 1
            - Name: DeployPublicApi
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: ECS
              InputArtifacts:
                - Name: BuildPublicApiOutput
              OutputArtifacts: []
              Configuration:
                ClusterName: !Ref EcsClusterName
                ServiceName: !Ref GreenProdPublicApiEcsService
                FileName: imagedefinitions.json
              RunOrder: 2
            - Name: DeployChromeExt
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts: []
              Configuration:
                ProjectName: !Ref GreenProdDeployChromeExtProject
              RunOrder: 3
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket 
#Outputs:
#  PipelineUrl:
#    Value: !Sub >-
#      https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
#    Description: CodePipeline URL
