version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd src/BrowserExts/ChromeExt
      - cp config.$ENVIRONMENT.js config.js
      - export DOCKER_RUN="docker run -v $PWD:/app -w /app node:9"
      - echo Run npm install...
      - $DOCKER_RUN npm install
      - echo Build app...
      - $DOCKER_RUN /bin/bash -c "npm install --global gulp && gulp"
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > ./build/version
  post_build:
    commands:
      - echo Pushing $PWD/build to S3...
      - aws s3 cp --recursive --acl public-read ./build/ s3://$S3_BUCKET_NAME/ 
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
