version: 0.2

phases:
  build:
    commands:
      - chmod +x ./build.sh
      - ./build.sh --target=DeployChromeExtFrame --env=$ENVIRONMENT --version-metadata=$CODEBUILD_RESOLVED_SOURCE_VERSION --aws-region=$AWS_DEFAULT_REGION --aws-account-id=$AWS_ACCOUNT_ID --web-s3-bucket=$S3_BUCKET_NAME --cdn-distribution-id=$CDN_DISTRIBUTION_ID 
