version: '3'
services:
  public-api:
    container_name: s2m-public-api
    build:
      context: .
      dockerfile: src/Services/Public.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5001:8080"
