version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build --file build.Dockerfile --tag s2m-build .
      - export DOCKER_RUN="docker run -v $PWD:/app -w /app s2m-build"
      - chmod +x ./build.sh
      - $DOCKER_RUN ./build.sh --target=UnitTest --env=$ENVIRONMENT --version-metadata=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Building the Docker image...
      - export IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build --build-arg APP_VERSION=$IMAGE_TAG --tag $IMAGE_REPO_NAME:$IMAGE_TAG --file src/Services/Public.API/Dockerfile .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf "[{\"name\":\"public-api\",\"imageUri\":\"${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}\"}]" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
