version: 0.2

phases:
  build:
    commands:
      - docker build --file build.Dockerfile --tag s2m-build .
      - export DOCKER_RUN="docker run -v $PWD:/app -v $HOME/.aws:/root/.aws -v /var/run/docker.sock:/var/run/docker.sock -w /app s2m-build"
      - chmod +x ./build.sh
      - $DOCKER_RUN ./build.sh --target=DeployPublicApi --env=$ENVIRONMENT --version-metadata=$CODEBUILD_RESOLVED_SOURCE_VERSION --image-repo-name=$IMAGE_REPO_NAME --aws-region=$AWS_DEFAULT_REGION --aws-account-id=$AWS_ACCOUNT_ID
artifacts:
  files:
    - imagedefinitions.json
